{
 "title": "my dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "frontend-service uptime",
   "type": "timeseries",
   "description": "show frontend service uptime",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{endpoint=\"frontend\",job=\"frontend-service\"}"
    }
   ]
  },
  {
   "title": "backend-service uptime",
   "type": "timeseries",
   "description": "show backend service uptime",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{container=\"backend\"}"
    }
   ]
  },
  {
   "title": "frontend-service http total for 4xx and 5xx",
   "type": "timeseries",
   "description": "frontend service 4xx and 5xx response",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "flask_http_request_total{status=~\"4.*\", service=\"frontend-service\"}"
    },
    {
     "expr": "flask_http_request_total{status=~\"5.*\", service=\"frontend-service\"}"
    }
   ]
  },
  {
   "title": "backend-service http for 4xx and 5xx",
   "type": "timeseries",
   "description": "backend service 4xx and 5xx response",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "flask_http_request_total{status=~\"4.*\",service=\"backend-service\"}"
    },
    {
     "expr": "flask_http_request_total{status=~\"5.*\",service=\"backend-service\"}"
    }
   ]
  },
  {
   "title": "uptime for frontend ,backend and trial container",
   "type": "timeseries",
   "description": "uptime for frontend ,backend and trial container",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "up{container=~\"backend|frontend|trial\"}"
    }
   ]
  },
  {
   "title": "http request exceptions by container",
   "type": "timeseries",
   "description": "total http request exceptions by container",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "flask_http_request_exceptions_total{}"
    }
   ]
  },
  {
   "title": "Jaeger traces by container",
   "type": "gauge",
   "description": "show Jaeger traces by container",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jaeger:traces_total) by (container)"
    }
   ]
  },
  {
   "title": "jaeger traces by container",
   "type": "timeseries",
   "description": "jaeger traces by container",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "sum(jaeger:traces_total) by (container)"
    }
   ]
  },
  {
   "title": "Error response rate per second",
   "type": "gauge",
   "description": "show error response rate per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(rate(flask_http_request_duration_seconds_count{status=~\"2.*|4.*\"}[$__rate_interval])))/(sum(rate(flask_http_request_duration_seconds_count[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Success response rate per second",
   "type": "gauge",
   "description": "show success response rate per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(flask_http_request_duration_seconds_count{status=~\"2.*|4.*\"}[$__rate_interval])))/(sum(rate(flask_http_request_duration_seconds_count[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "average http response time",
   "type": "timeseries",
   "description": "show average http response time",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum[$__rate_interval])/rate(flask_http_request_duration_seconds_count[$__rate_interval])) by (endpoint, path)"
    }
   ]
  },
  {
   "title": "http median response time",
   "type": "timeseries",
   "description": "show median http response time",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (container, path, le) (rate(flask_http_request_duration_seconds_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "http 99th precentile response time",
   "type": "timeseries",
   "description": "show http 99th precentile response time by container and path",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (container, path, le) (rate(flask_http_request_duration_seconds_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "cpu usage by container",
   "type": "timeseries",
   "description": "process cpu usage in seconds by container",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "targets": [
    { "expr": "process_cpu_seconds_total{}" }
   ]
  },
  {
   "title": "cpu util by node",
   "type": "stat",
   "description": "show cpu utilization by node",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m"
    }
   ]
  },
  {
   "title": "container memory usage",
   "type": "timeseries",
   "description": "container memory usage in bytes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "targets": [
    { "expr": "container_memory_usage_bytes{}" }
   ]
  },
  {
   "title": "memory util by node",
   "type": "stat",
   "description": "show memory utilization by node",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio"
    }
   ]
  },
  {
   "title": "io util by node",
   "type": "timeseries",
   "description": "show disk io util by note",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_seconds:rate5m{}"
    }
   ]
  },
  {
   "title": "network receive by node",
   "type": "timeseries",
   "description": "show network receive by node",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 62 },
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate5m{}"
    }
   ]
  },
  {
   "title": "network transmit by node",
   "type": "timeseries",
   "description": "show network transmit by node",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
   "targets": [
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate5m{}"
    }
   ]
  }
 ]
}